---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: cosmonic-labs
spec:
  type: team
  profile:
    displayName: Cosmonic Labs
  children: []

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: example-app
  description: A simple WebAssembly application example
  tags:
    - backend
    - webassembly
spec:
  type: service
  owner: cosmonic-labs
  lifecycle: development
